import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Suspense example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="py-4 shadow-sm ">
          <div className="container flex gap-5">
            <Link href="/no-suspense">No suspense</Link>
            <Link href="/with-suspense">With suspense</Link>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
